# Generated by Django 2.1.7 on 2019-03-09 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrpt', '0002_eventdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='enrollment',
            field=models.IntegerField(default=1, help_text='Classroom enrollment on the event date', validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
