# Generated by Django 2.1.7 on 2019-03-24 13:41

from django.db import migrations, models
import wrpt.models


class Migration(migrations.Migration):

    dependencies = [
        ('wrpt', '0003_count_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrptuser',
            name='hideChangePasswordLink',
            field=models.BooleanField(default=False, help_text="If checked, hides the 'Change password' link from the user (password can still be changed by staff).", verbose_name='Hide change password link'),
        ),
        migrations.AlterField(
            model_name='program',
            name='schoolYear',
            field=models.CharField(default=wrpt.models.defaultSchoolYear, help_text='Ex: 2013-2014', max_length=9, validators=[wrpt.models.schoolYearValidator], verbose_name='School year'),
        ),
    ]
